### ISSUE TITLE
anti AFK plugin

### ISSUE THREAD

**Issue by unixfox** [bolt-rip/config-pgm#6]
A plugin that kick AFK players after a certain amount of time.

Walrus visor is good candidate: https://gitlab.com/WalrusNetwork/infrastructure/walrus-visor but it lacks of a config.yml in order to set the amount of time after the player get kicked.

**Comment by Pablete1234** [comment]
You need no plugin, it's built-in into vanilla server.properties

**Comment by unixfox** [comment]
> You need no plugin, it's built-in into vanilla server.properties

No it's not. The vanilla mc server disconnect a client if it doesn't respond to the requests from the server after a certain amount of time and doesn't disconnect a client if it doesn't move.

**Comment by Pablete1234** [comment]
@unixfox we have tested and used it, if you stay afk after the period of time it does kick you
